name: base_style_sheet
description: Um package auxiliar para manter os componentes visuais globais de um aplicativo multi-repositório e mono-repositório.
homepage: https://www.github.com/leobidoous
repository: https://www.github.com/leobidoous/base_style_sheet
issue_tracker: https://www.github.com/leobidoous/base_style_sheet/issues
version: 1.4.1

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  pinput: ^5.0.1
  shimmer: ^3.0.0
  flutter_svg: ^2.2.0
  file_picker: ^10.3.1
  photo_view: ^0.15.0
  fluttertoast: ^8.2.12
  image_picker: ^1.1.2
  auto_size_text: ^3.0.0
  webview_flutter: ^4.13.0
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.4.1
  webview_flutter_web: ^0.2.3+4
  webview_flutter_android: ^4.10.0
  custom_refresh_indicator: ^4.0.1
  webview_flutter_wkwebview: ^3.23.0
  syncfusion_flutter_pdfviewer: ^30.2.5
  cached_network_image_platform_interface: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
